spring.application.name=ProyectoSpringBoot01
server.port=7001
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/resources/**
valor.secreto=Este es mi valor secreto
management.endpoints.web.exposure.include=shutdown,startup,loggers,info,health
management.endpoint.shutdown.enabled=true
logging.file.path=/home/rusok/Descargas
logging.file.name=/home/rusok/Descargas/borralo.log
logging.level.com.pepe.proyectospringboot01.Controllers=DEBUG
logging.level.org.springframework=INFO
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){cyan} %clr(%-5level){yellow} %clr(-->) {magenta} %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{26} - %msg%n
logging.logback.rollingpolicy.file-name-pattern=borralo-%d{yyyy-MM-dd}-%i.log
logging.logback.rollingpolicy.max-file-size=10MB
server.compression.enabled=true