spring.application.name=ProyectoSpringBoot01
server.port=7001
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/resources/**
valor.secreto=Este es mi valor secreto
management.endpoints.web.exposure.include=shutdown,startup,loggers,info,health
management.endpoint.shutdown.enabled=true